### ISSUE TITLE
App crashes when using Bluemix account with EU-GB region only

### ISSUE THREAD

**Issue by RickHagenaars** [osis/cf-apps-ios#116]
I've downloaded the app, selected the Bluemix platform and logged in with my bluemix account.
After logging in the app seemed to crash. When restarting it immediately crashed again.

I figured that this would be caused because I do not have the default region active on my (trial) account. I've uninstalled the app so I could select a platform again. When selecting the platform "other" and providing the cf api endpoint "https://api.eu-gb.bluemix.net" everything is working just fine. Maybe you can integrate support for different regions within Bluemix, or make clear that the predefined Bluemix platform is for the default region only.

**Comment by osis** [comment]
@RickHagenaars Thanks for reporting this! The app is definitely due for a sync of [CF API endpoints](http://cf-api-version.mybluemix.net/) that are in the wild.

**Comment by osis** [comment]
@RickHagenaars Update should be [in the store](https://itunes.apple.com/ca/app/cf-apps/id1070237537?mt=8). Thanks for the bug report!
