### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mgwalker** [osis/cf-apps-ios#26]
Hi there!  Looks like a cool app.  I'm curious what license you're releasing the source code under.

**Comment by osis** [comment]
Hey Greg, I'm using the MIT license for this project. You can find it here...

https://github.com/Osis/cf-apps-ios/blob/master/LICENSE

I'll make sure to update the year.

**Comment by mgwalker** [comment]
Oh whoops, I didn't even see the LICENSE file.  My apologies for not paying more attention!  Thanks for the info!  😄
