### ISSUE TITLE
Updating organizations

### ISSUE THREAD

**Issue by adammeyer** [osis/cf-apps-ios#8]
After login, I'm stuck on the "Updating Organizations" screen. Any ideas of this to try?

**Comment by osis** [comment]
Hey @adammeyer,

there are a few things that can contribute to that issue. 
- Have you tried the newest version of the application?
- Are the permissions of the account you're logging in okay? Does it have access to at least one organization?
- Which Cloud Foundry provider are you trying to use?

Thanks for the feedback. Would love to help you solve this issue.
